name: reusetestresult
description: Reuse good test result
author: Tony Do
configuration:
  properties:
    bucket:
      type: string
    repo:
      type: string
    includes:
      type: string
    step:
      type: string
  additionalProperties: false
